const instruments = require("./instruments.json");

//author: ChipMC/hhhzzzsss
module.exports = [
  ...new Array(35).fill(null), // offset
  { pitch: 10, instrument: instruments.basedrum },
  { pitch: 6, instrument: instruments.basedrum },
  { pitch: 6, instrument: instruments.hat },
  { pitch: 8, instrument: instruments.snare },
  { pitch: 6, instrument: instruments.hat },
  { pitch: 4, instrument: instruments.snare },
  { pitch: 6, instrument: instruments.basedrum },
  { pitch: 22, instrument: instruments.snare },
  { pitch: 13, instrument: instruments.basedrum },
  { pitch: 22, instrument: instruments.snare },
  { pitch: 15, instrument: instruments.basedrum },
  { pitch: 18, instrument: instruments.snare },
  { pitch: 20, instrument: instruments.basedrum },
  { pitch: 23, instrument: instruments.basedrum },
  { pitch: 17, instrument: instruments.snare },
  { pitch: 23, instrument: instruments.basedrum },
  { pitch: 24, instrument: instruments.snare },
  { pitch: 8, instrument: instruments.snare },
  { pitch: 13, instrument: instruments.snare },
  { pitch: 18, instrument: instruments.hat },
  { pitch: 18, instrument: instruments.snare },
  { pitch: 1, instrument: instruments.hat },
  { pitch: 13, instrument: instruments.snare },
  { pitch: 2, instrument: instruments.hat },
  { pitch: 13, instrument: instruments.snare },
  { pitch: 9, instrument: instruments.hat },
  { pitch: 2, instrument: instruments.hat },
  { pitch: 8, instrument: instruments.hat },
  { pitch: 22, instrument: instruments.basedrum },
  { pitch: 15, instrument: instruments.basedrum },
  { pitch: 13, instrument: instruments.snare },
  { pitch: 8, instrument: instruments.snare },
  { pitch: 8, instrument: instruments.hat },
  { pitch: 3, instrument: instruments.hat },
  { pitch: 20, instrument: instruments.hat },
  { pitch: 23, instrument: instruments.hat },
  { pitch: 24, instrument: instruments.hat },
  { pitch: 24, instrument: instruments.hat },
  { pitch: 17, instrument: instruments.hat },
  { pitch: 11, instrument: instruments.hat },
  { pitch: 18, instrument: instruments.hat },
  { pitch: 9, instrument: instruments.hat },
  { pitch: 5, instrument: instruments.hat },
  { pitch: 22, instrument: instruments.hat },
  { pitch: 19, instrument: instruments.snare },
  { pitch: 17, instrument: instruments.hat },
  { pitch: 22, instrument: instruments.hat },
  { pitch: 22, instrument: instruments.snare },
  { pitch: 24, instrument: instruments.chime },
  { pitch: 24, instrument: instruments.chime },
  { pitch: 21, instrument: instruments.hat },
  { pitch: 14, instrument: instruments.basedrum },
  { pitch: 7, instrument: instruments.basedrum }
]